language: c
compiler: gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y valgrind
script:
  - make debug
  - valgrind tests/test_1
  - make
  - tests/test_1
notifications:
  email: false

